DROP TABLE IF EXISTS film_locations CASCADE;
DROP TABLE IF EXISTS movies CASCADE;
DROP TABLE IF EXISTS icons CASCADE;

CREATE TABLE movies (
  id SERIAL PRIMARY KEY NOT NULL,
  movie_name VARCHAR(255) NOT NULL,
  year_filmed SMALLINT NOT NULL
);

CREATE TABLE icons (
  id SERIAL PRIMARY KEY NOT NULL,
  icon_url VARCHAR(255) NOT NULL
);

CREATE TABLE film_locations (
  id SERIAL PRIMARY KEY NOT NULL,
  city VARCHAR(255) NOT NULL,
  lat DECIMAL NOT NULL,
  lng DECIMAL NOT NULL,
  movie_id INTEGER REFERENCES movies(id) ON DELETE CASCADE,
  icon_id INTEGER REFERENCES icons(id) ON DELETE CASCADE
);
